services:
  analysis-env:
    image: /farkasvic/CPeptide-Diabetes-Regression-Group-42:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64