name: diabetesgroup42env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.3.2
  - requests=2.32.4
  - seaborn=0.13.2
  - matplotlib=3.10.6
  - altair=5.5.0
  - scikit-learn=1.7.2
