name: diabetesgroup42env
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.6
  - altair=5.5.0
  - requests=2.32.4
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - python=3.11
  - ipykernel=6.30.1
  - pingouin=0.5.5
  - jupyterlab>=4.5.0
  - nb_conda_kernels>=2.5.1
  - nbconvert=7.16.6
  - pydantic=2.12.5
  - numpy<2.0
  - click=8.3.1
  - pytest=9.0.2
  - pip=25.3
  - pip:
      - deepchecks
      - great-expectations
      - pandera
      - anywidget
