name: diabetesgroup42env
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.6
  - altair=5.5.0
  - requests=2.32.4
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - python=3.12
  - ipykernel=6.30.1
  - pingouin=0.5.5
